In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
import matplotlib.pyplot as plt

In [10]:
df=pd.read_csv('new.csv')

In [11]:
nominal_cols=['Department','City']

In [12]:
ordinal_cols=['Education_Level','Satisfaction_Rating']

In [13]:
for col in nominal_cols:
    print(f"{col}: {df[col].unique()}")
print()
for col in ordinal_cols:
    print(f"{col}: {df[col].unique()}")

Department: ['Sales' 'Marketing' 'IT' 'HR' 'Finance']
City: ['Chicago' 'New York' 'Los Angeles' 'Houston' 'Miami' 'Berkley']

Education_Level: ["Bachelor's" "Master's" 'High School' 'PhD']
Satisfaction_Rating: ['High' 'Medium' 'Low' 'Very High']


In [14]:
df.shape

(30, 5)

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
#Create an Object.
encoder=OneHotEncoder(sparse_output=False)
temp=encoder.fit_transform(df[nominal_cols])

In [17]:
print(type(temp))
temp.shape
import sys
sys.getsizeof(temp)/1024

<class 'numpy.ndarray'>


2.703125

In [18]:
encoder.transform([['Marketing','Miami']])

C:\Users\STUDENT\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.]])

In [19]:
encoder.inverse_transform([[0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.]])

array([['Marketing', 'Miami']], dtype=object)

In [20]:
#Different method if we want Multi-Dim Array
encoder.inverse_transform(np.array([0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.]).reshape(1,11))

array([['Marketing', 'Miami']], dtype=object)

In [21]:
encoder.feature_names_in_

array(['Department', 'City'], dtype=object)

In [22]:
encoder.get_feature_names_out()

array(['Department_Finance', 'Department_HR', 'Department_IT',
       'Department_Marketing', 'Department_Sales', 'City_Berkley',
       'City_Chicago', 'City_Houston', 'City_Los Angeles', 'City_Miami',
       'City_New York'], dtype=object)

In [23]:
#When sparse_output is True. Even by default it is true.
encoder=OneHotEncoder(sparse_output=True)

In [24]:
temp=encoder.fit_transform(df[nominal_cols])

In [25]:
print(type(temp))
temp.shape

<class 'scipy.sparse._csr.csr_matrix'>


(30, 11)

In [26]:
print(temp.shape)
print(temp.data)
print(temp.indices) #indices of each row where non-zero occurs
print(temp.indptr) #represents the separation between rows.

(30, 11)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 4  6  3 10  2  8  1  6  0  7  4  9  2 10  3  8  1  7  0  6  4  5  2  8
  3 10  1  7  0  6  4  5  2 10  3  8  1  6  0  7  4  9  2 10  3  6  1  8
  0  7  4  9  2 10  3  6  1  8  0  7]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60]


In [27]:
import sys
sys.getsizeof(temp)/1024

0.0546875

In [28]:
encoder.transform([['Marketing','Miami']]).toarray() #typecasting to array

C:\Users\STUDENT\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.]])

In [29]:
encoder.inverse_transform(np.array([0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.]).reshape(1,11))

array([['Marketing', 'Miami']], dtype=object)

colinearity will not change the output, we just omit one.

In [39]:
encoder=OneHotEncoder(drop='first', min_frequency=6)

In [40]:
temp=encoder.fit_transform(df[nominal_cols])

In [41]:
temp.shape

(30, 8)

In [42]:
df['Department'].value_counts()

Department
Sales        6
Marketing    6
IT           6
HR           6
Finance      6
Name: count, dtype: int64

In [43]:
df['City'].value_counts()

City
Chicago        7
New York       6
Los Angeles    6
Houston        6
Miami          3
Berkley        2
Name: count, dtype: int64

In [44]:
temp.shape

(30, 8)

In [55]:
encoder.transform([['Marketing','Miami']]).toarray() 

C:\Users\STUDENT\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 0., 0., 0., 0., 1.]])

In [56]:
encoder.transform([['Marketing','Miami']]).toarray()

C:\Users\STUDENT\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 0., 0., 0., 0., 1.]])

In [58]:
encoder.inverse_transform(np.array([0., 0., 1., 0., 0., 0., 0., 1.]).reshape(1,-1))

array([['Marketing', 'infrequent_sklearn']], dtype=object)

In [66]:
encoder=OneHotEncoder(drop='first', max_categories=5)

In [67]:
temp=encoder.fit_transform(df[nominal_cols])
temp.shape

(30, 8)

In [68]:
encoder.get_feature_names_out()

array(['Department_IT', 'Department_Marketing', 'Department_Sales',
       'Department_infrequent_sklearn', 'City_Houston',
       'City_Los Angeles', 'City_New York', 'City_infrequent_sklearn'],
      dtype=object)

In [69]:
df['Education_Level'].value_counts()

Education_Level
Bachelor's     12
Master's        8
High School     6
PhD             4
Name: count, dtype: int64

In [71]:
df['Satisfaction_Rating'].value_counts()

Satisfaction_Rating
High         9
Medium       9
Low          6
Very High    6
Name: count, dtype: int64

In [73]:
from sklearn.preprocessing import OrdinalEncoder

In [76]:
for col in nominal_cols:
    print(f"{col}: {df[col].unique()}")
print()
for col in ordinal_cols:
    print(f"{col}: {df[col].unique()}")

Department: ['Sales' 'Marketing' 'IT' 'HR' 'Finance']
City: ['Chicago' 'New York' 'Los Angeles' 'Houston' 'Miami' 'Berkley']

Education_Level: ["Bachelor's" "Master's" 'High School' 'PhD']
Satisfaction_Rating: ['High' 'Medium' 'Low' 'Very High']


In [79]:
encoder = OrdinalEncoder(categories=[["Bachelor's","Master's",'High School','PhD'],['High','Medium','Low','Very High']])
ord_temp=encoder.fit_transform(df[ordinal_cols])
print(type(ord_temp))
ord_temp.shape
ord_temp

<class 'numpy.ndarray'>


array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [1., 3.],
       [0., 1.],
       [3., 0.],
       [2., 2.],
       [0., 1.],
       [1., 3.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [3., 3.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [1., 3.],
       [0., 0.],
       [3., 1.],
       [2., 2.],
       [0., 0.],
       [1., 3.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [3., 3.]])

In [81]:
encoder.transform([["Bachelor's",'High']])

C:\Users\STUDENT\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0., 0.]])

In [82]:
encoder.inverse_transform(np.array([0.,0.]).reshape(1,-1))

array([["Bachelor's", 'High']], dtype=object)

In [83]:
y=np.array(['cat1']*15 + ['cat2']*10 + ['cat3']*8 +['cat4']*4 + ['cat5']*2).reshape(-1,1)
y
enc=OrdinalEncoder(min_frequency=5, categories=[['cat4','cat5','cat3','cat2','cat1']])

In [85]:
enc.fit_transform(y)

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.]])